### ISSUE TITLE
[arm plugin]  "make install" does not copy libarmPlugin.so from build directory bin/<arch>/Release/lib/ to install target directory $CMAKE_INSTALL_PREFIX/deployment_tools/inference_engine/lib/<arch>/

### ISSUE THREAD

**Issue by okih** [openvinotoolkit/openvino_contrib#180]
After building with "cmake  -D CMAKE_BUILD_TYPE=Release  -D CMAKE_INSTALL_PREFIX=somewhere <<snipped>> -D IE_EXTRA_MODULES=../../openvino_contrib/modules  .. " and "make" , "make install" does not copy libarmPlugin.so from build directory bin/armv7l/Release/lib/ to install target directory somewhere/deployment_tools/inference_engine/lib/armv7l/ .

So https://storage.openvinotoolkit.org/repositories/openvino /packages/2021.4/l_openvino_toolkit_runtime_raspbian_p_2021.4.582.tgz does not include libarmPlugin.so in spite of "plugin name="CPU" location="libarmPlugin.so" " definition in plugin.xml .

Regards,

**Comment by alvoron** [comment]
@okih thank you for raising the issue!

Intel Distribution of OpenVINO does not contain ARM CPU Plugin, the plugin is distributed via source codes only.
So, it's expected that there is no `libarmPlugin.so` in `l_openvino_toolkit_runtime_raspbian_p_2021.4.582.tgz`

However, we have an issue with `make install` - indeed it does not copy `libarmPlugin.so` to `lib/armv7l` folder. This issue is being discussed and will be fixed shortly.
Now I'd suggest you to use `cmake -DCMAKE_INSTALL_PREFIX=$STAGING_DIR -P cmake_install.cmake` instead of `make install`. It copies ARM CPU plugin library to the needed directory.

Also, you may use [armplg_build.sh](https://github.com/openvinotoolkit/openvino_contrib/blob/master/modules/arm_plugin/armplg_build.sh) script to build all components and prepare the package with 1 click,

**Comment by okih** [comment]
Thank you for reply.

Regarding the raspbian runtime package in the toolkit storage I had supposed it had been built as including arm plugin, since plugin.xml had had "name CPU" definition.
I confirmed that plugin.xml had armPlugin line in ether way building with "-D IE_EXTRA_MODULES" option or without it.
I applogize my misunderstanding.

I copied libarmPlugin.so manually to the target directory to build binaries for my raspberry pi. I will check suggested methods.

Best Regards,

**Comment by alvoron** [comment]
`make install` command should works fine on master branch.
Fix has been implemented on OpenVINO side: https://github.com/openvinotoolkit/openvino/pull/6861
ARM CPU plugin single build script will be updated too: https://github.com/openvinotoolkit/openvino_contrib/pull/182

**Comment by alvoron** [comment]
@okih did you have a chance to check `make install` command?
If so and you don't observe any issues - are you OK to close this issue?

**Comment by okih** [comment]
Hi alvoron,
Sorry for my late reply.
I have confirmed that "make install" works as expected. Please close this issue.
Best Regards,
